# Generated by Django 5.1.6 on 2025-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='faltas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
