# Generated by Django 5.1.6 on 2025-02-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_consultas_faltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='faltas',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='faltas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
